// ──────────────────────────────────────────────
//  Localization
// ──────────────────────────────────────────────
const LANGS = {
  en: {
    nativeName: 'English',
    defaultListName: '🛒 Shopping List',
    addPlaceholder: 'Add an item…',
    addBtn: 'Add',
    sortTitle: 'Move checked to bottom',
    clearCheckedTitle: 'Remove all checked items',
    menuTitle: 'Menu',
    langMenuBtn: 'Language',
    emptyTitle: 'Your list is empty',
    emptyHint: 'Add items above to get started',
    checkedSection: 'Checked',
    dragHandle: 'Drag to reorder',
    deleteItem: 'Delete',
    noChecked: 'No checked items to remove',
    removed: n => `Removed ${n} item${n === 1 ? '' : 's'}`,
    cleared: 'Cleared all items',
    clearAll: 'Clear all items',
    info_updated:     (n, l) => `${n} updated '${l}'`,
    info_add:         (n, l) => `${n} added an item to '${l}'`,
    info_check:       (n, l) => `${n} checked an item on '${l}'`,
    info_delete:      (n, l) => `${n} deleted an item from '${l}'`,
    info_clearChecked:(n, l) => `${n} cleared checked items on '${l}'`,
    info_clearAll:    (n, l) => `${n} cleared all items on '${l}'`,
    info_rename:      (n, l) => `${n} renamed the list to '${l}'`,
    info_edit:        (n, l) => `${n} edited an item on '${l}'`,
    info_reorder:     (n, l) => `${n} reordered '${l}'`,
    info_sortToggle:  (n, l) => `${n} toggled sort on '${l}'`,
    info_changed:     (n, l) => `${n} changed '${l}'`,
  },
  de: {
    nativeName: 'Deutsch',
    defaultListName: '🛒 Einkaufsliste',
    addPlaceholder: 'Element hinzufügen…',
    addBtn: 'Hinzufügen',
    sortTitle: 'Erledigte nach unten sortieren',
    clearCheckedTitle: 'Abgehakte Elemente entfernen',
    menuTitle: 'Menü',
    langMenuBtn: 'Sprache',
    emptyTitle: 'Deine Liste ist leer',
    emptyHint: 'Füge oben Elemente hinzu um loszulegen',
    checkedSection: 'Erledigt',
    dragHandle: 'Zum Verschieben ziehen',
    deleteItem: 'Löschen',
    noChecked: 'Keine abgehakten Elemente',
    removed: n => `${n} Element${n === 1 ? '' : 'e'} entfernt`,
    cleared: 'Alle Elemente gelöscht',
    clearAll: 'Alle Elemente löschen',
    info_updated:     (n, l) => `${n} hat '${l}' aktualisiert`,
    info_add:         (n, l) => `${n} hat ein Element zu '${l}' hinzugefügt`,
    info_check:       (n, l) => `${n} hat ein Element in '${l}' abgehakt`,
    info_delete:      (n, l) => `${n} hat ein Element aus '${l}' gelöscht`,
    info_clearChecked:(n, l) => `${n} hat abgehakte Elemente in '${l}' entfernt`,
    info_clearAll:    (n, l) => `${n} hat alle Elemente in '${l}' gelöscht`,
    info_rename:      (n, l) => `${n} hat die Liste in '${l}' umbenannt`,
    info_edit:        (n, l) => `${n} hat ein Element in '${l}' bearbeitet`,
    info_reorder:     (n, l) => `${n} hat '${l}' neu angeordnet`,
    info_sortToggle:  (n, l) => `${n} hat die Sortierung in '${l}' umgeschaltet`,
    info_changed:     (n, l) => `${n} hat '${l}' geändert`,
  }
};