// ──────────────────────────────────────────────
//  Localization
// ──────────────────────────────────────────────
const LANGS = {
  en: {
    nativeName: 'English',
    defaultListName: '🛒 Shopping List',
    addPlaceholder: 'Add an item…',
    addBtn: 'Add',
    sortTitle: 'Move checked to bottom',
    clearCheckedTitle: 'Remove all checked items',
    menuTitle: 'Menu',
    langMenuBtn: 'Language',
    emptyTitle: 'Your list is empty',
    emptyHint: 'Add items above to get started',
    checkedSection: 'Checked',
    dragHandle: 'Drag to reorder',
    deleteItem: 'Delete',
    noChecked: 'No checked items to remove',
    removed: n => `Removed ${n} item${n === 1 ? '' : 's'}`,
    cleared: 'Cleared all items',
    clearAll: 'Clear all items',
    info_updated:     (n, l) => `${n} updated '${l}'`,
    info_add:         (n, l) => `${n} added an item to '${l}'`,
    info_check:       (n, l) => `${n} checked an item on '${l}'`,
    info_delete:      (n, l) => `${n} deleted an item from '${l}'`,
    info_clearChecked:(n, l) => `${n} cleared checked items on '${l}'`,
    info_clearAll:    (n, l) => `${n} cleared all items on '${l}'`,
    info_rename:      (n, l) => `${n} renamed the list to '${l}'`,
    info_edit:        (n, l) => `${n} edited an item on '${l}'`,
    info_reorder:     (n, l) => `${n} reordered '${l}'`,
    info_sortToggle:  (n, l) => `${n} toggled sort on '${l}'`,
    info_changed:     (n, l) => `${n} changed '${l}'`,
  },
  de: {
    nativeName: 'Deutsch',
    defaultListName: '🛒 Einkaufsliste',
    addPlaceholder: 'Element hinzufügen…',
    addBtn: 'Hinzufügen',
    sortTitle: 'Erledigte nach unten sortieren',
    clearCheckedTitle: 'Abgehakte Elemente entfernen',
    menuTitle: 'Menü',
    langMenuBtn: 'Sprache',
    emptyTitle: 'Deine Liste ist leer',
    emptyHint: 'Füge oben Elemente hinzu um loszulegen',
    checkedSection: 'Erledigt',
    dragHandle: 'Zum Verschieben ziehen',
    deleteItem: 'Löschen',
    noChecked: 'Keine abgehakten Elemente',
    removed: n => `${n} Element${n === 1 ? '' : 'e'} entfernt`,
    cleared: 'Alle Elemente gelöscht',
    clearAll: 'Alle Elemente löschen',
    info_updated:     (n, l) => `${n} hat '${l}' aktualisiert`,
    info_add:         (n, l) => `${n} hat ein Element zu '${l}' hinzugefügt`,
    info_check:       (n, l) => `${n} hat ein Element in '${l}' abgehakt`,
    info_delete:      (n, l) => `${n} hat ein Element aus '${l}' gelöscht`,
    info_clearChecked:(n, l) => `${n} hat abgehakte Elemente in '${l}' entfernt`,
    info_clearAll:    (n, l) => `${n} hat alle Elemente in '${l}' gelöscht`,
    info_rename:      (n, l) => `${n} hat die Liste in '${l}' umbenannt`,
    info_edit:        (n, l) => `${n} hat ein Element in '${l}' bearbeitet`,
    info_reorder:     (n, l) => `${n} hat '${l}' neu angeordnet`,
    info_sortToggle:  (n, l) => `${n} hat die Sortierung in '${l}' umgeschaltet`,
    info_changed:     (n, l) => `${n} hat '${l}' geändert`,
  },
  zh: {
    nativeName: '中文',
    defaultListName: '🛒 购物清单',
    addPlaceholder: '添加项目…',
    addBtn: '添加',
    sortTitle: '将已勾选项移至底部',
    clearCheckedTitle: '移除所有已勾选项',
    menuTitle: '菜单',
    langMenuBtn: '语言',
    emptyTitle: '你的列表为空',
    emptyHint: '在上方添加项目以开始',
    checkedSection: '已完成',
    dragHandle: '拖拽重新排序',
    deleteItem: '删除',
    noChecked: '没有可移除的已勾选项',
    removed: n => `已移除 ${n} 项`,
    cleared: '已清除所有项目',
    clearAll: '清除所有项目',
    info_updated:     (n, l) => `${n} 更新了 '${l}'`,
    info_add:         (n, l) => `${n} 在 '${l}' 中添加了一个项目`,
    info_check:       (n, l) => `${n} 在 '${l}' 中勾选了一个项目`,
    info_delete:      (n, l) => `${n} 从 '${l}' 中删除了一个项目`,
    info_clearChecked:(n, l) => `${n} 清除了 '${l}' 中的已勾选项`,
    info_clearAll:    (n, l) => `${n} 清除了 '${l}' 中的所有项目`,
    info_rename:      (n, l) => `${n} 将列表重命名为 '${l}'`,
    info_edit:        (n, l) => `${n} 编辑了 '${l}' 中的一个项目`,
    info_reorder:     (n, l) => `${n} 重新排序了 '${l}'`,
    info_sortToggle:  (n, l) => `${n} 切换了 '${l}' 的排序`,
    info_changed:     (n, l) => `${n} 更改了 '${l}'`,
  },
  hi: {
    nativeName: 'हिन्दी',
    defaultListName: '🛒 खरीदारी सूची',
    addPlaceholder: 'आइटम जोड़ें…',
    addBtn: 'जोड़ें',
    sortTitle: 'चेक किए गए आइटम नीचे ले जाएं',
    clearCheckedTitle: 'सभी चेक किए गए आइटम हटाएं',
    menuTitle: 'मेनू',
    langMenuBtn: 'भाषा',
    emptyTitle: 'आपकी सूची खाली है',
    emptyHint: 'शुरू करने के लिए ऊपर आइटम जोड़ें',
    checkedSection: 'चेक किए गए',
    dragHandle: 'क्रम बदलने के लिए खींचें',
    deleteItem: 'हटाएं',
    noChecked: 'हटाने के लिए कोई चेक किया गया आइटम नहीं',
    removed: n => `${n} आइटम हटाए गए`,
    cleared: 'सभी आइटम हटाए गए',
    clearAll: 'सभी आइटम हटाएं',
    info_updated:     (n, l) => `${n} ने '${l}' को अपडेट किया`,
    info_add:         (n, l) => `${n} ने '${l}' में एक आइटम जोड़ा`,
    info_check:       (n, l) => `${n} ने '${l}' पर एक आइटम चेक किया`,
    info_delete:      (n, l) => `${n} ने '${l}' से एक आइटम हटाया`,
    info_clearChecked:(n, l) => `${n} ने '${l}' पर चेक किए गए आइटम साफ किए`,
    info_clearAll:    (n, l) => `${n} ने '${l}' पर सभी आइटम साफ किए`,
    info_rename:      (n, l) => `${n} ने सूची का नाम '${l}' रख दिया`,
    info_edit:        (n, l) => `${n} ने '${l}' पर एक आइटम संपादित किया`,
    info_reorder:     (n, l) => `${n} ने '${l}' को पुनः क्रमित किया`,
    info_sortToggle:  (n, l) => `${n} ने '${l}' पर सॉर्टिंग टॉगल की`,
    info_changed:     (n, l) => `${n} ने '${l}' को बदला`,
  },
  es: {
    nativeName: 'Español',
    defaultListName: '🛒 Lista de compras',
    addPlaceholder: 'Añadir un elemento…',
    addBtn: 'Añadir',
    sortTitle: 'Mover marcados al final',
    clearCheckedTitle: 'Eliminar todos los elementos marcados',
    menuTitle: 'Menú',
    langMenuBtn: 'Idioma',
    emptyTitle: 'Tu lista está vacía',
    emptyHint: 'Añade elementos arriba para comenzar',
    checkedSection: 'Marcados',
    dragHandle: 'Arrastra para reordenar',
    deleteItem: 'Eliminar',
    noChecked: 'No hay elementos marcados para eliminar',
    removed: n => `Eliminado(s) ${n} elemento(s)`,
    cleared: 'Se borraron todos los elementos',
    clearAll: 'Borrar todos los elementos',
    info_updated:     (n, l) => `${n} actualizó '${l}'`,
    info_add:         (n, l) => `${n} añadió un elemento a '${l}'`,
    info_check:       (n, l) => `${n} marcó un elemento en '${l}'`,
    info_delete:      (n, l) => `${n} eliminó un elemento de '${l}'`,
    info_clearChecked:(n, l) => `${n} limpió los elementos marcados en '${l}'`,
    info_clearAll:    (n, l) => `${n} limpió todos los elementos en '${l}'`,
    info_rename:      (n, l) => `${n} renombró la lista a '${l}'`,
    info_edit:        (n, l) => `${n} editó un elemento en '${l}'`,
    info_reorder:     (n, l) => `${n} reordenó '${l}'`,
    info_sortToggle:  (n, l) => `${n} alternó el orden en '${l}'`,
    info_changed:     (n, l) => `${n} cambió '${l}'`,
  },
  pt: {
    nativeName: 'Português',
    defaultListName: '🛒 Lista de compras',
    addPlaceholder: 'Adicionar um item…',
    addBtn: 'Adicionar',
    sortTitle: 'Mover verificados para o final',
    clearCheckedTitle: 'Remover todos os itens verificados',
    menuTitle: 'Menu',
    langMenuBtn: 'Idioma',
    emptyTitle: 'Sua lista está vazia',
    emptyHint: 'Adicione itens acima para começar',
    checkedSection: 'Verificados',
    dragHandle: 'Arraste para reordenar',
    deleteItem: 'Excluir',
    noChecked: 'Nenhum item verificado para remover',
    removed: n => `Removido(s) ${n} item(ns)`,
    cleared: 'Todos os itens foram removidos',
    clearAll: 'Limpar todos os itens',
    info_updated:     (n, l) => `${n} atualizou '${l}'`,
    info_add:         (n, l) => `${n} adicionou um item a '${l}'`,
    info_check:       (n, l) => `${n} verificou um item em '${l}'`,
    info_delete:      (n, l) => `${n} excluiu um item de '${l}'`,
    info_clearChecked:(n, l) => `${n} limpou os itens verificados em '${l}'`,
    info_clearAll:    (n, l) => `${n} limpou todos os itens em '${l}'`,
    info_rename:      (n, l) => `${n} renomeou a lista para '${l}'`,
    info_edit:        (n, l) => `${n} editou um item em '${l}'`,
    info_reorder:     (n, l) => `${n} reordenou '${l}'`,
    info_sortToggle:  (n, l) => `${n} alternou a classificação em '${l}'`,
    info_changed:     (n, l) => `${n} alterou '${l}'`,
  },
  fr: {
    nativeName: 'Français',
    defaultListName: '🛒 Liste de courses',
    addPlaceholder: 'Ajouter un article…',
    addBtn: 'Ajouter',
    sortTitle: 'Déplacer les cochés en bas',
    clearCheckedTitle: 'Supprimer tous les articles cochés',
    menuTitle: 'Menu',
    langMenuBtn: 'Langue',
    emptyTitle: 'Votre liste est vide',
    emptyHint: 'Ajoutez des articles ci-dessus pour commencer',
    checkedSection: 'Cochés',
    dragHandle: 'Glisser pour réorganiser',
    deleteItem: 'Supprimer',
    noChecked: 'Aucun article coché à supprimer',
    removed: n => `${n} article(s) supprimé(s)`,
    cleared: 'Tous les articles ont été effacés',
    clearAll: 'Effacer tous les articles',
    info_updated:     (n, l) => `${n} a mis à jour '${l}'`,
    info_add:         (n, l) => `${n} a ajouté un article à '${l}'`,
    info_check:       (n, l) => `${n} a coché un article sur '${l}'`,
    info_delete:      (n, l) => `${n} a supprimé un article de '${l}'`,
    info_clearChecked:(n, l) => `${n} a effacé les articles cochés sur '${l}'`,
    info_clearAll:    (n, l) => `${n} a effacé tous les articles sur '${l}'`,
    info_rename:      (n, l) => `${n} a renommé la liste en '${l}'`,
    info_edit:        (n, l) => `${n} a modifié un article sur '${l}'`,
    info_reorder:     (n, l) => `${n} a réorganisé '${l}'`,
    info_sortToggle:  (n, l) => `${n} a basculé le tri sur '${l}'`,
    info_changed:     (n, l) => `${n} a modifié '${l}'`,
  },
  it: {
    nativeName: 'Italiano',
    defaultListName: '🛒 Lista della spesa',
    addPlaceholder: 'Aggiungi un elemento…',
    addBtn: 'Aggiungi',
    sortTitle: 'Sposta gli elementi spuntati in basso',
    clearCheckedTitle: 'Rimuovi tutti gli elementi spuntati',
    menuTitle: 'Menu',
    langMenuBtn: 'Lingua',
    emptyTitle: 'La tua lista è vuota',
    emptyHint: 'Aggiungi elementi qui sopra per iniziare',
    checkedSection: 'Spuntati',
    dragHandle: 'Trascina per riordinare',
    deleteItem: 'Elimina',
    noChecked: 'Nessun elemento spuntato da rimuovere',
    removed: n => `Rimossi ${n} element${n === 1 ? 'o' : 'i'}`,
    cleared: 'Cancellati tutti gli elementi',
    clearAll: 'Cancella tutti gli elementi',
    info_updated:     (n, l) => `${n} ha aggiornato '${l}'`,
    info_add:         (n, l) => `${n} ha aggiunto un elemento a '${l}'`,
    info_check:       (n, l) => `${n} ha spuntato un elemento su '${l}'`,
    info_delete:      (n, l) => `${n} ha eliminato un elemento da '${l}'`,
    info_clearChecked:(n, l) => `${n} ha rimosso gli elementi spuntati da '${l}'`,
    info_clearAll:    (n, l) => `${n} ha cancellato tutti gli elementi da '${l}'`,
    info_rename:      (n, l) => `${n} ha rinominato la lista in '${l}'`,
    info_edit:        (n, l) => `${n} ha modificato un elemento su '${l}'`,
    info_reorder:     (n, l) => `${n} ha riordinato '${l}'`,
    info_sortToggle:  (n, l) => `${n} ha attivato/disattivato l'ordinamento su '${l}'`,
    info_changed:     (n, l) => `${n} ha modificato '${l}'`,
  },
  ru: {
    nativeName: 'Русский',
    defaultListName: '🛒 Список покупок',
    addPlaceholder: 'Добавить элемент…',
    addBtn: 'Добавить',
    sortTitle: 'Переместить отмеченные вниз',
    clearCheckedTitle: 'Удалить все отмеченные элементы',
    menuTitle: 'Меню',
    langMenuBtn: 'Язык',
    emptyTitle: 'Ваш список пуст',
    emptyHint: 'Добавьте элементы выше, чтобы начать',
    checkedSection: 'Отмеченные',
    dragHandle: 'Перетащите для сортировки',
    deleteItem: 'Удалить',
    noChecked: 'Нет отмеченных элементов для удаления',
    removed: n => `Удалено ${n} элемент(ов)`,
    cleared: 'Все элементы очищены',
    clearAll: 'Очистить все элементы',
    info_updated:     (n, l) => `${n} обновил(а) '${l}'`,
    info_add:         (n, l) => `${n} добавил(а) элемент в '${l}'`,
    info_check:       (n, l) => `${n} отметил(а) элемент в '${l}'`,
    info_delete:      (n, l) => `${n} удалил(а) элемент из '${l}'`,
    info_clearChecked:(n, l) => `${n} очистил(а) отмеченные элементы в '${l}'`,
    info_clearAll:    (n, l) => `${n} очистил(а) все элементы в '${l}'`,
    info_rename:      (n, l) => `${n} переименовал(а) список в '${l}'`,
    info_edit:        (n, l) => `${n} отредактировал(а) элемент в '${l}'`,
    info_reorder:     (n, l) => `${n} изменил(а) порядок в '${l}'`,
    info_sortToggle:  (n, l) => `${n} переключил(а) сортировку в '${l}'`,
    info_changed:     (n, l) => `${n} изменил(а) '${l}'`,
  },
  pl: {
    nativeName: 'Polski',
    defaultListName: '🛒 Lista zakupów',
    addPlaceholder: 'Dodaj element…',
    addBtn: 'Dodaj',
    sortTitle: 'Przenieś odhaczone na dół',
    clearCheckedTitle: 'Usuń wszystkie odhaczone elementy',
    menuTitle: 'Menu',
    langMenuBtn: 'Język',
    emptyTitle: 'Twoja lista jest pusta',
    emptyHint: 'Dodaj elementy powyżej, aby rozpocząć',
    checkedSection: 'Odhaczone',
    dragHandle: 'Przeciągnij, aby zmienić kolejność',
    deleteItem: 'Usuń',
    noChecked: 'Brak odhaczonych elementów do usunięcia',
    removed: n => `Usunięto ${n} element${n === 1 ? '' : (n < 5 ? 'y' : 'ów')}`,
    cleared: 'Wyczyszczono wszystkie elementy',
    clearAll: 'Wyczyść wszystkie elementy',
    info_updated:     (n, l) => `${n} zaktualizował(a) '${l}'`,
    info_add:         (n, l) => `${n} dodał(a) element do '${l}'`,
    info_check:       (n, l) => `${n} odhaczył(a) element na '${l}'`,
    info_delete:      (n, l) => `${n} usunął(a) element z '${l}'`,
    info_clearChecked:(n, l) => `${n} wyczyścił(a) odhaczone elementy na '${l}'`,
    info_clearAll:    (n, l) => `${n} wyczyścił(a) wszystkie elementy na '${l}'`,
    info_rename:      (n, l) => `${n} zmienił(a) nazwę listy na '${l}'`,
    info_edit:        (n, l) => `${n} edytował(a) element na '${l}'`,
    info_reorder:     (n, l) => `${n} zmienił(a) kolejność na '${l}'`,
    info_sortToggle:  (n, l) => `${n} przełączył(a) sortowanie na '${l}'`,
    info_changed:     (n, l) => `${n} zmienił(a) '${l}'`,
  },
  nl: {
    nativeName: 'Nederlands',
    defaultListName: '🛒 Boodschappenlijst',
    addPlaceholder: 'Voeg een item toe…',
    addBtn: 'Toevoegen',
    sortTitle: 'Verplaats aangevinkte items naar beneden',
    clearCheckedTitle: 'Verwijder alle aangevinkte items',
    menuTitle: 'Menu',
    langMenuBtn: 'Taal',
    emptyTitle: 'Je lijst is leeg',
    emptyHint: 'Voeg hierboven items toe om te beginnen',
    checkedSection: 'Aangevinkt',
    dragHandle: 'Sleep om te herschikken',
    deleteItem: 'Verwijderen',
    noChecked: 'Geen aangevinkte items om te verwijderen',
    removed: n => `${n} item${n === 1 ? '' : 's'} verwijderd`,
    cleared: 'Alle items gewist',
    clearAll: 'Wis alle items',
    info_updated:     (n, l) => `${n} heeft '${l}' bijgewerkt`,
    info_add:         (n, l) => `${n} heeft een item toegevoegd aan '${l}'`,
    info_check:       (n, l) => `${n} heeft een item aangevinkt op '${l}'`,
    info_delete:      (n, l) => `${n} heeft een item verwijderd uit '${l}'`,
    info_clearChecked:(n, l) => `${n} heeft aangevinkte items gewist op '${l}'`,
    info_clearAll:    (n, l) => `${n} heeft alle items gewist op '${l}'`,
    info_rename:      (n, l) => `${n} heeft de lijst hernoemd naar '${l}'`,
    info_edit:        (n, l) => `${n} heeft een item bewerkt op '${l}'`,
    info_reorder:     (n, l) => `${n} heeft '${l}' opnieuw gerangschikt`,
    info_sortToggle:  (n, l) => `${n} heeft sortering ingeschakeld op '${l}'`,
    info_changed:     (n, l) => `${n} heeft '${l}' gewijzigd`,
  }
};